http_config: Add host
prometheus/common pull request #549
Opened 2023-12-08 23:00 UTC by jkroepke

Follow-up: https://github.com/prometheus/prometheus/pull/13157

Host allows to override the hostname from URL. This can be useful if DNS is not stable but the endpoint required an valid host.

2024-01-11 19:32 UTC, SuperQ requested changes

2024-01-11 19:32 UTC, SuperQ commented on config/http_config.go
> +	Host string `yaml:"host" json:"host"`
If this is optional, it should be `omitempty` I think.

```suggestion
	Host string `yaml:"host,omitempty" json:"host,omitempty"`
```

2024-01-15 10:36 UTC, SuperQ approved these changes

2024-02-03 08:41 UTC, jkroepke commented
Can I help here?

2024-02-28 16:56 UTC, merged

2024-03-06 11:37 UTC, bboreham commented
Unfortunately this clashes with the field of the same Yaml name in Prometheus Docker SD.