promslog: Use the default timezone (again)
prometheus/common pull request #739
Opened 2024-12-05 15:32 UTC by beorn7

This reverts commit 145b50adb4ece06ea09a5b0abcbedb76bd1b123a.

See discussion on Slack. We should first decide which log format we want before changing it from what is already released in prometheus/prometheus.

UPDATE:

This is the new commit description:

As per the dev-summit discussion, we want to use the default timezone
as selected by slog after all rather than a hardcoded UTC.

(This was accidentally introduced earlier when moving from gokit to
slog, but then switched back to hardcoded UTC in PR https://github.com/prometheus/common/pull/735.)

Environments that have configured UTC anyway won't see any difference,
but those with other timezones configured will see the configured
timezone for the timestamps in their logs. This is in line with how
slog behaves by default.

Example timestamp _before_ this change and also _after_ this change
with UTC configured in the environment via a suitable way (e.g.
setting `TZ=UTC` on Linux):

    time=2025-04-10T12:00:38.179Z

Example timestamp _after_ this change with location Europe/Berlin,
i.e. timezone is CET or CEST:

    time=2025-04-10T14:00:03.120+02:00

Note that the precise delta to UTC is in the timestamp. So this change
will also be transparent to the usual logs processing tools.

2024-12-05 16:13 UTC, SuperQ requested changes
There is no need to revert this. This is a bug fix for the previous release where we did not correctly make timestamps UTC.

2024-12-05 21:21 UTC, beorn7 commented
It's a feature, not a bug… :)

But even if we come to the conclusion in the end that it is a bug fix, let's first come to that conclusion before we start cutting actual releases with the changed log format.

See also https://docs.google.com/document/d/1uurQCi5iVufhYHGlBZ8mJMK_freDFKPG0iYBQqJ9fvA/edit?pli=1&tab=t.0#bookmark=id.l370cy8m6ef4 .

2025-03-31 13:58 UTC, SuperQ approved these changes
Approved at 2025-03-31 Dev Summit

2025-03-31 13:58 UTC, SuperQ commented
I guess we need to do a bit of a rebase revert.

2025-04-10 11:44 UTC, beorn7 commented
Yeah, other things happened with fine tuning the timestamp format. I'll push a new commit shortly.

2025-04-10 12:07 UTC, beorn7 commented
Here we are. @SuperQ PHAL.

2025-04-10 12:24 UTC, merged